Chat back
aurelien-brabant/ft_transcendance pull request #29
Opened 2022-02-20 19:49 UTC by matboivin

Start implementation of channels and messages: entities, DTO, methods (get the users in a channel, number of users in channel, all the messages sent by a user...)

2022-02-24 20:38 UTC, aurelien-brabant commented on src/nestjs-back/src/channels/channels.controller.ts
> +    findAllByOwner(@Param('ownerId') ownerId: string) {
Not very RESTful, filtering is usually done through the use of query params
For example:
`/channels?owner_id=345`
`/channels?visibility=public&owner_id=345`

Creating controller routes for that purpose is rarely seen and, from what I know, isn't really a RESTful practice.

2022-02-24 21:09 UTC, aurelien-brabant requested changes
Awesome work, although some things must be corrected/improved
See my comments for more info

2022-02-24 21:09 UTC, aurelien-brabant commented on src/nestjs-back/src/messages/dto/update-message.dto.ts
> +export class UpdateMessageDto {
Use `PartialType`
see https://docs.nestjs.com/openapi/mapped-types

2022-02-24 21:09 UTC, aurelien-brabant commented on src/nestjs-back/src/messages/messages.controller.ts
> +    @Get('/sender/:senderId')
If you want to filter by sender use the `/messages?sender=id`.
If you want to access the sender of the message this route may make sense, but if I understand this code correctly this is only achieving filtering by sender

2022-02-24 21:09 UTC, aurelien-brabant commented on src/nestjs-back/src/messages/messages.controller.ts
> +    @Get('/sender/:senderId')
See my comments on channels controller for more info

2022-02-24 21:09 UTC, aurelien-brabant commented on src/nestjs-back/src/messages/messages.controller.ts
> +    getSender(@Param('id') id: string) {
same comments, don't specialize routes like that

2022-02-24 21:09 UTC, aurelien-brabant commented on src/nestjs-back/src/users/dto/seed-user.dto.ts
>  import { IsString, IsEmail, IsOptional, IsInt, IsPhoneNumber } from 'class-validator';
is seed DTO still of any use? We should probably consider to remove it

2022-02-24 21:09 UTC, aurelien-brabant commented on src/nestjs-back/src/users/users.controller.ts
> +    getOwnedChannels(@Param('id') id: string) {
here specialization makes sense because we are getting these specifics items through the route. This is good.

2022-02-26 15:24 UTC, matboivin commented
Thanks a lot @aurelien-brabant !!! Fixing and improving all of this right now! Will also update #30 (still draft)

2022-02-26 15:26 UTC, aurelien-brabant commented
Glad to here that, feel free to request a new review when it's done :)

2022-02-27 15:23 UTC, matboivin commented on src/nestjs-back/src/channels/dto/create-channel.dto.ts
> +    readonly isPublic: boolean;
Good idea, changed!

2022-02-27 16:37 UTC, matboivin commented
@aurelien-brabant Fixes made!

2022-03-03 16:24 UTC, aurelien-brabant approved these changes
LGTM, merging

2022-03-03 16:24 UTC, merged